# Uncomment this line to define a global platform for your project
platform :ios, ‘7.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'Yookos' do

pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

end

target 'YKSIATests' do

end

target 'YKSIAUITests' do

end

